###
POST http://localhost:8080/api/v1/book
Content-Type: application/json

{
  "name": "Harry Potter and the Goblet of Fire",
  "author": "JK Rowling",
  "date_published": "2020-01-01",
  "quantity": 1
}

###
DELETE http://localhost:8080/api/v1/book/1

###
PUT http://localhost:8080/api/v1/book/3?quantity=10
Content-Type: application/json
